#Show harvest level name next to the tool icon
show_harvest_level_name = true
#Show block required harvest level in tooltips. NEVER = never shows, ADVANCED = shows when shift is held or advanced tooltips are enabled, ALWAYS = always shows.
#Allowed Values: NEVER, ADVANCED, ALWAYS
block_harvest_levels_display_mode = "ADVANCED"
#Show tool harvest level in tooltips. NEVER = never shows, ADVANCED = shows when shift is held or advanced tooltips are enabled, ALWAYS = always shows.
#Allowed Values: NEVER, ADVANCED, ALWAYS
tool_harvest_levels_display_mode = "ADVANCED"

#Colors for vanilla harvest levels, in hex format or color name
[vanilla_level_colors]
	STONE = "#808080"
	NETHERITE = "#443a3b"
	IRON = "#cecaca"
	WOOD = "#8b5a2b"
	GOLD = "#ecd93f"
	DIAMOND = "#2cbaa8"

